about/urls.py
from django.urls import re_path
from .views import index

urlpatterns = [
    re_path(r'^$', index, name='about')
]

contact/urls.py
from django.urls import re_path, path, include
from .views import index, message_post, message_table

app_name = 'contact'

urlpatterns = [
    re_path(r'^$', index, name='contact'),
    re_path(r'^add_message', message_post, name='add_message'),
    re_path(r'^result_table', message_table, name='result_table')
]

experience/urls.py
from django.urls import re_path
from .views import index

urlpatterns = [
    re_path(r'^$', index, name='experience')
]

lab_4/urls.py
from django.urls import re_path
from .views import index

urlpatterns = [
    re_path(r'^$', index, name='chat-box')
]

landing/urls.py
from django.urls import re_path
from .views import index

urlpatterns = [
    re_path(r'^$', index, name='index')
]

login/urls.py
from django.urls import re_path, include

urlpatterns = [
    re_path('', include('django.contrib.auth.urls'))
]

uts/urls.py
from django.contrib import admin
from django.urls import re_path, path
from django.conf.urls import include
from landing.views import index as landing

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^landing/', include('landing.urls')),
    re_path(r'^experience/', include('experience.urls')),
    re_path(r'^about/', include('about.urls')),
    # re_path(r'^contact/', include('contact.urls')),
    re_path(r'^contact/', include('contact.urls', namespace='contact')),
    re_path(r'^chatbox', include('lab_4.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^$', landing, name='index')
]

about/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models
# import datetime
# import pytz

# time_zone = pytz.timezone('Asia/Jakarta')
# date = datetime.datetime.now().date()
# time = datetime.time(23, 59)
# # combite to datetime
# date_time = datetime.datetime.combine(date, time)
# # make time zone aware
# date_time = time_zone.localize(date_time)
# # convert to UTC
# utc_date_time = date_time.astimezone(pytz.utc)
# # get time
# utc_time = utc_date_time.time()


# Create your models here.

class Message(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

experience/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

landing/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms


class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }
    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous',
                           widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

about/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    response = {}
    return render(request, 'about.html', response)

contact/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    response = {'message_form': Message_Form}
    return render(request, 'email.html', response)


def message_post(request):
    response = {}
    form = Message_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'], message=response['message'])
        message.save()
        html = 'contact/templates/form_result.html'
        return render(request, 'form_result.html', response)
    else:
        return HttpResponseRedirect('/')


@login_required
def message_table(request):
    response = {}
    message = Message.objects.all()
    response['message'] = message
    html = 'templates/table.html'
    return render(request, 'table.html', response)

# @login_required
# def secret_page(request):
#     return render_to_response("table.html")

experience/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    response = {}
    return render(request, 'experience.html', response)

lab_4/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    response = {}
    return render(request, 'lab_4/lab_4.html', response)

landing/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    response = {}
    return render(request, 'index.html', response)

login/views.py
from django.shortcuts import render

# Create your views here.

about/templates/about.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>My Page - Peter Wenji</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type='image/x-icon'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link
            href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat|Sacramento"
            rel="stylesheet"
    />
    <script src="https://kit.fontawesome.com/215f700fce.js"></script>
</head>
<body>
<div class="napbar">
    <nav class="napbar navbar fixed-top navbar-expand-lg navbar-fixed-top">
        <div class="navbar-collapse collapse w-100 dual-collapse2 order-1 order-md-0">
            <ul class="navbar-nav ml-auto text-center">
                <li class="nav-item active">
                    <a class="nav-link" href="/landing">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about"><span class="underline">About</span></a>
                </li>
            </ul>
        </div>
        <div class="mx-auto my-2 order-0 order-md-1 position-relative">
            <a class="inactiveLink mx-auto" href="">
                <img src="{% static 'images/logo.png' %}" class="rounded-circle" height="120" width="120">
            </a>
            <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse"
                    data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
            <ul class="navbar-nav mr-auto text-center">
                <li class="nav-item">
                    <a class="nav-link" href="/experience">Experience & Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
</div>
<div class="isi">
    <div class="profile">
        <h1> About.</h1>
        {#        <img class="tree" src="{% static 'images/tree.png' %}" alt="tree-img"/>#}
        <p class="intro">
            Saya seorang software engineer, yang berfokus di bidang web development. saya sangat suka mengerjakan
            website
            terutama bagian back-end, selain web saya juga menguasai pemograman berbasis python dan java.
        </p>

    </div>

</div>
<div class="isi">
        <div class="intro">
        <h2>latar belakang pendidkan</h2>
        <ul>
            <li><h3>SDK GRACIA BANDUNG</h3>
                <p>2005 - 2011</p>
            </li>
            <li><h3>SMPK GAMALIEL Bandung</h3>
                <p>2011 - 2014</p></li>
            <li><h3>SMAK GAMALIEL Bandung</h3>
                <p>2014 - 2017</p></li>
            <li><h3>S1 - STMIK LIKMI Bandung</h3>
                <p>Jurusan Teknik Informatika</p>
                <p>2017 - sekarang</p></li>
        </ul>
    </div>
</div>
<div class="foot">
    <footer class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-left">
            <div class="row">
                <div class="col-md-6 mt-md-0 mt-3">
                    <img src="{% static 'images/logo.png' %}" alt="logo" height="120" width="120">
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-3 mb-md-0 mb-3">
                    <h5 class="text-uppercase">Hit me up</h5>
                    <ul class="ss list-unstyled">
                        <li>
                            <a href="https://www.facebook.com/peter.wenyi" target="_blank"
                            >Facebook</a>
                        </li>
                        <li>
                            <a
                                    href="https://mail.google.com/mail/?view=cm&fs=1&to=pieterjake321@gmail.com"
                                    target="_top"
                            >Mail</a>
                        </li>
                        <li>
                            <a href="https://wa.me/638121769414/?text=Hi" target="_blank">
                                Whatsapp
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'chat-box' %}" target="_self">Chat Room</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}" target="_self">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">© 2019 Copyright
        </div>
    </footer>
</div>
<button onclick="topFunction()" id="myBtn" title="Go to top">⇑ Top</button>
<button class="chati" onclick="topFunction()" id="myBtn">Chat Room</button>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

contact/templates/email.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Page - Peter Wenji</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type='image/x-icon'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link
            href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat|Sacramento"
            rel="stylesheet"
    />
    {#    <script src="https://kit.fontawesome.com/215f700fce.js"></script>#}

</head>
<body>
<div class="napbar">
    <nav class="napbar navbar fixed-top navbar-expand-lg navbar-fixed-top">
        <div class="navbar-collapse collapse w-100 dual-collapse2 order-1 order-md-0">
            <ul class="navbar-nav ml-auto text-center">
                <li class="nav-item active">
                    <a class="nav-link" href="/landing">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto my-2 order-0 order-md-1 position-relative">
            <a class="inactiveLink mx-auto" href="">
                <img src="{% static 'images/logo.png' %}" class="rounded-circle" height="120" width="120">
            </a>
            <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse"
                    data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
            <ul class="navbar-nav mr-auto text-center">
                <li class="nav-item">
                    <a class="nav-link" href="/experience">Experience & Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact"><span class="underline">Contact</span></a>
                </li>
            </ul>
        </div>
    </nav>
</div>
<h1>contact Me</h1>
<div class="box">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="box-part text-center">
                    <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
                    <div class="title">
                        <h4>Instagram</h4>
                    </div>
                    <div class="text">
                        <span>my photo collection.</span>
                    </div>
                    <a href="https://www.instagram.com/yungfeldt/" target="_blank">Learn More</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="box-part text-center">
                    <i class="fa fa-whatsapp fa-3x" aria-hidden="true"></i>
                    <div class="title">
                        <h4>Whatsapp</h4>
                    </div>
                    <div class="text">
                        <span>chat me via whatsapp.</span>
                    </div>
                    <a href="https://wa.me/638121769414/?text=Hi" target="_blank">Learn More</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="box-part text-center">
                    <i class="fa fa-facebook fa-3x" aria-hidden="true"></i>
                    <div class="title">
                        <h4>Facebook</h4>
                    </div>
                    <div class="text">
                        <span>see my profile via facebook</span>
                    </div>
                    <a href="https://www.facebook.com/peter.wenyi">Learn More</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="box-part text-center">
                    <i class="fa fa-pinterest-p fa-3x" aria-hidden="true"></i>
                    <div class="title">
                        <h4>Pinterest</h4>
                    </div>
                    <div class="text">
                        <span>collection of my favorite picture</span>
                    </div>
                    <a href="https://www.pinterest.com/peterwenyi/" target="_blank">Learn More</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="box-part text-center">
                    <i class="fa fa-google-plus fa-3x" aria-hidden="true"></i>
                    <div class="title">
                        <h4>Gmail</h4>
                    </div>
                    <div class="text">
                        <span>email me via gmail</span>
                    </div>
                    <a href="https://mail.google.com/mail/?view=cm&fs=1&to=pieterjake321@gmail.com" target="_blank">Learn
                        More</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="box-part text-center">
                    <i class="fa fa-github fa-3x" aria-hidden="true"></i>
                    <div class="title">
                        <h4>Github</h4>
                    </div>
                    <div class="text">
                        <span>it ain't much but it's honest work</span>
                    </div>
                    <a href="https://github.com/Canary1711" target="_blank">Learn More</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <h2><a href="{% url 'chat-box' %}">Chat Room</a></h2>
</div>
<div class="forms">
    <section name="form">
        <h2>Send Message</h2>
        <form id="form" method="POST" action="{% url 'contact:add_message' %}">
            <div class="form-group">
                {% csrf_token %}
                {{ message_form }}
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
            <br>
            <br>
            <br>
            <h3><a href="{% url 'contact:result_table' %}">List Message</a></h3>
        </form>
    </section>
    {#{% endblock %}#}
</div>
<div class="foot">
    <footer class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-left">
            <div class="row">
                <div class="col-md-6 mt-md-0 mt-3">
                    <img src="{% static 'images/logo.png' %}" alt="logo" height="120" width="120">
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-3 mb-md-0 mb-3">
                    <h5 class="text-uppercase">Hit me up</h5>
                    <ul class="ss list-unstyled">
                        <li>
                            <a href="https://www.facebook.com/peter.wenyi" target="_blank"
                            >Facebook</a>
                        </li>
                        <li>
                            <a
                                    href="https://mail.google.com/mail/?view=cm&fs=1&to=pieterjake321@gmail.com"
                                    target="_top"
                            >Mail</a>
                        </li>
                        <li>
                            <a href="https://wa.me/638121769414/?text=Hi" target="_blank">
                                Whatsapp
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'chat-box' %}" target="_self">Chat Room</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}" target="_self">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">© 2019 Copyright
        </div>
    </footer>
</div>
<button onclick="topFunction()" id="myBtn" title="Go to top">⇑ Top</button>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

contact/templates/form_result.html
{% extends "layout/base.html" %}

{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
    <div class="forms">
    <h1>Thank You!</h1>
    <textarea readonly rows="15" class="form-control">&quot;{{ message }}&quot;-
{{ name }}
by {{ email }}
</textarea>
{% endblock %}
</div>

{% block footer %}
    <p> &copy; {{ name }} </p>
{% endblock %}

contact/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type='image/x-icon'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link
            href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat|Sacramento"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/lab_4.css' %}"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
</head>
<body>
{% include 'partials/header.html' %}
<div class="isi">
    {% block content %} {% endblock %}
</div>
{% include 'partials/footer.html' %}
<button onclick="topFunction()" id="myBtn" title="Go to top">⇑ Top</button>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/lab_4.js' %}"></script>
</body>
</html>

contact/templates/partials/footer.html
{% load static %}
<div class="foot">
    <footer class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-left">
            <div class="row">
                <div class="col-md-6 mt-md-0 mt-3">
                    <img src="{% static 'images/logo.png' %}" alt="logo" height="120" width="120">
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-3 mb-md-0 mb-3">
                    <h5 class="text-uppercase">Hit me up</h5>
                    <ul class="ss list-unstyled">
                        <li>
                            <a href="https://www.facebook.com/peter.wenyi" target="_blank"
                            >Facebook</a>
                        </li>
                        <li>
                            <a
                                    href="https://mail.google.com/mail/?view=cm&fs=1&to=pieterjake321@gmail.com"
                                    target="_top"
                            >Mail</a>
                        </li>
                        <li>
                            <a href="https://wa.me/638121769414/?text=Hi" target="_blank">
                                Whatsapp
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'chat-box' %}" target="_self">Chat Room</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}" target="_self">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">© 2019 Copyright
        </div>
    </footer>
</div>

contact/templates/partials/header.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{% load static %}
{#{% block header %}#}
    <div class="napbar">
        <nav class="napbar navbar fixed-top navbar-expand-lg navbar-fixed-top">
            <div class="navbar-collapse collapse w-100 dual-collapse2 order-1 order-md-0">
                <ul class="navbar-nav ml-auto text-center">
                    <li class="nav-item active">
                        <a class="nav-link" href="/landing">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                </ul>
            </div>
            <div class="mx-auto my-2 order-0 order-md-1 position-relative">
                <a class="inactiveLink mx-auto" href="">
                    <img src="{% static 'images/logo.png' %}" class="rounded-circle" height="120" width="120">
                </a>
                <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse"
                        data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
                <ul class="navbar-nav mr-auto text-center">
                    <li class="nav-item">
                        <a class="nav-link" href="/experience">Experience & Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact"><span class="underline">Contact</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
{#{% endblock %}#}
{#</body>#}
{#</html>#}

contact/templates/table.html
{% extends "layout/base.html" %}
{% block title %} Kumpulan pesan {% endblock %}
{% block content %}
    <div class="isi">
        <h2>Kumpulan Pesan</h2>
        <table class="pad table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Nama</th>
                <th scope="col">Email</th>
                <th scope="col">Pesan</th>
                <th scope="col">Dibuat pada</th>
            </tr>
            </thead>
            <tbody>
            {% for i in message %}
                {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
                    <tr class="warning alert-danger"> {% else %}
                    <tr class="succsess alert-success">
                {% endif %}
            <td>{{ forloop.counter }}</td>
            {#            <td>{{ j }}</td>#}
            <td>{{ i.name }}</td>
            <td>{{ i.email }}</td>
            <td>{{ i.message }}</td>
            <td>{{ i.created_date.time }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <button><a href="{% url 'logout' %}">Logout</a></button>
    </div>
{% endblock %}

lab_4/templates/lab_4/lab_4.html
{% extends "lab_4/layout/ChatBase.html" %}
{% block chatBox %}
    <!-- ChatBox Section -->
    <section name="Chatbox">
        <div class="wrapper">
            <div class="profile chat-box">
                <div class="chat-head">
                    <h2>Chat</h2>
                    <hr>
                    <img
                            src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_down-16.png"
                            title="Expand Arrow" width="16">
                </div>
                <div class="chat-body">
                    <div id="chatBody" class="msg-insert">
                    </div>
                    <div class="chat-text">
                        <textarea id="textA" placeholder="Press Enter"></textarea>
                    </div>
                    <button id="btnText" type="submit" class="btn btn-primary">
                        Enter!
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}